arm:
    gazebo_ros_control:
        pid_gains:
            # these gains are used by the gazebo_ros_control plugin
            joint1:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            joint2:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            joint3:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            joint4:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            joint5:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            gripper_right_joint1:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.2}

            # the following gains are used by the gazebo_mimic_joint plugin
            gripper_right_joint2:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.2}
            gripper_left_joint1:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.2}
            gripper_left_joint2:
                {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.2}

