controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - gripper
  - name: fake_gripper_controller
    joints:
      - gripper_r1
initial:  # Define initial robot poses.
  - group: arm
    pose: home